apiVersion: v1
kind: Service
metadata:
  name: testl-lb
spec:
  selector:
    # app: httpd
    traefik-ingress: abcd
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer