apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "ss-cookie"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      # container port
      port: 8080
      # internal exposed port
      targetPort: 8080